name: Build and Release Mirla HD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Zip Mirla Theme
        # Stand one directory above the theme...
        working-directory: input/themes
        # ...and zip the mirlaTheme folder itself.
        run: zip -r "${{ github.workspace }}/mirlaTheme.zip" mirlaTheme

      - name: Zip Mirla Plugin
        # Run from the root of the repository...
        # ...and zip the mirlaPlugin folder itself.
        run: zip -r "${{ github.workspace }}/mirlaPlugin.zip" mirlaPlugin

      # This ensures manual runs get the 'manual-build' tag instead of 'main'
      - name: Set Release Variables
        id: vars
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "RELEASE_NAME=Release ${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=manual-build" >> $GITHUB_ENV
            echo "RELEASE_NAME=Manual Build" >> $GITHUB_ENV
          fi

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mirlaTheme.zip
            mirlaPlugin.zip
            MirlaDataEditor.html
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          body: |
            ### 📦 Installation Files
            To use this environment, please download both **`mirlaTheme.zip`** and **`mirlaPlugin.zip`** from the Assets section below.
            
            ### 🛠️ Mirla Data Editor
            Also included in this release is the **`MirlaDataEditor.html`** file. You can download and open this single file directly in your browser to structure, edit, and export your collection's data and images before publishing.
            
            ### 📖 Documentation
            For complete installation instructions, data structuring guidelines, and a list of interactive components, please check the [main repository README](../../).
          draft: false
          prerelease: false
          generate_release_notes: true